Server:
  Env: development
  RunMode: debug
  Port: 8080
  TokenExpire: 8
  SecretKey: "12345678900987654321"
Database:
  Server: localhost
  Port: 1433
  User: sa
  Pass: p@ssw0rd
  DatabaseName: Consolidated
LoggerFile:
  RootPath: ./logs/
