### Find All 
GET http://localhost:8080/api/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjM3Nzc5MDcsInVzZXJuYW1lIjoiYWRtaW4ifQ.rg4mn53XQu1CSGCzvjKqNv_KxTstpFHAX_-FnMsgJqk


### Find All 
GET http://localhost:8080/api/user/ HTTP/1.1