### Find All 
GET http://localhost:8080/api/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyUmVxdWVzdCI6IntcIkVtcENvZGVcIjpcIkMwMDAxXCIsXCJVc2VyXCI6XCJKdXRpcG9uZyBTdWJpblwiLFwiUGVybWlzc2lvbnNcIjpcIkFkbWluXCIsXCJUcmFuc2F0aW9uSWRcIjpcIlwifSIsImV4cCI6MTYyNDEwMzE1OH0.Ye4FEVExJdXrUjOcYHopAfqHCLRPGoz4_t6BUyUA4As


### Find All 
GET http://localhost:8080/api/user/ HTTP/1.1