### Find All 
GET http://localhost:8080/api/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjM3Nzk0ODcsInVzZXJuYW1lIjoiYWRtaW4ifQ.DWngqjs75fT4RwHAZ-nOeXkythehlWcpHNB9uGw73nY


### Find All 
GET http://localhost:8080/api/user/ HTTP/1.1