### test fail
POST   http://localhost:8080/fee/inward/v1/iwrm HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyUmVxdWVzdCI6IntcIlVzZXJJZFwiOlwiSU5XQVJEXCIsXCJVc2VyTmFtZVwiOlwiSU5XQVJEXCJ9IiwiZXhwIjoxNjI2MjAwMjg5fQ.d2TVqC-MwPh4lPLQWL1d1F3CG4X6zmJl4np7Yhfdt8k
Content-Type: application/json

{
    "channelID": "asd",
    "refId": "",
    "transDate": "",
    "transTime": "",
    "reqDetail": {
        "accountNo": "",
        "cifNo": "",
        "feeChannel": "",
        "transactionType": "",
        "chargeType": "",
        "orderingType": "",
        "searchPayInFull": "",
        "benCountry": "",
        "purpose": "",
        "fromCCY": "",
        "toCCY": "",
        "amountFrom": 222222222222222.11,
        "amountTo": 222222222222222.34,
        "exchangeRate": 333333333333333.6,
        "effectiveDate": "",
        "feeType": ""
    }
}

### test data all
POST  http://localhost:8080/fee/inward/v1/iwrm HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyUmVxdWVzdCI6IntcIlN5c3RlbUlkXCI6XCJTMDAwMVwiLFwiRW1wQ29kZVwiOlwiRTAwMDFcIixcIlVzZXJcIjpcIlUwMDAxXCIsXCJQZXJtaXNzaW9uc1wiOlwiQWRtaW5cIixcIlRyYW5zYXRpb25JZFwiOlwiXCJ9IiwiZXhwIjoxNjI1MjM1NDc2fQ.PG6k4zxV2r6MatUcdtp_gk9Y9u4ulrkWwdGID3rXPaM
Content-Type: application/json

{
    "channelID": "channelID",
    "refId": "15xxxxxxxxxxxxx",
    "transDate": "8xxxxxxx",
    "transTime": "8xxxxxxx",
    "reqDetail": {
        "accountNo": "20xxxxxxxxxxxxxxxxxx",
        "cifNo": "20xxxxxxxxxxxxxxxxxx",
        "feeChannel": "20xxxxxxxxxxxxxxxxxx",
        "transactionType": "10xxxxxxxx",
        "chargeType": "3xx",
        "orderingType": "10xxxxxxxx",
        "searchPayInFull": "1",
        "depositWithdraw":"10xxxxxxxx",
        "benCountry": "2x",
        "purpose": "10xxxxxxxx",
        "fromCCY": "AED",
        "toCCY": "AED",
        "amountFrom": 12345.3476,
        "amountTo": 222222222222222.34,
        "exchangeRate": 3333333333333330.69,
        "effectiveDate": "20210324",
        "feeType": "20xxxxxxxxxxxxxxxxxx"
    }
    
}

### test data all
POST  http://localhost:8080/api/v1/inwardfee HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyUmVxdWVzdCI6IntcIlN5c3RlbUlkXCI6XCJTMDAwMVwiLFwiRW1wQ29kZVwiOlwiRTAwMDFcIixcIlVzZXJcIjpcIlUwMDAxXCIsXCJQZXJtaXNzaW9uc1wiOlwiQWRtaW5cIixcIlRyYW5zYXRpb25JZFwiOlwiXCJ9IiwiZXhwIjoxNjI1MjM1NDc2fQ.PG6k4zxV2r6MatUcdtp_gk9Y9u4ulrkWwdGID3rXPaM
Content-Type: application/json

{
    "channelID": "channelID",
    "refId": "15xxxxxxxxxxxxx",
    "transDate": "20210324",
    "transTime": "8xxxxxxx",
    "reqDetail": {
        "accountNo": "20xxxxxxxxxxxxxxxxxx",
        "cifNo": "20xxxxxxxxxxxxxxxxxx",
        "feeChannel": "SWIFT",
        "transactionType": "CASH",
        "chargeType": "OUR",
        "orderingType": "retail",
        "searchPayInFull": "Y",
        "depositWithdraw":"Withdraw",
        "benCountry": "AX",
        "purpose": "10xxxxxxxx",
        "fromCCY": "AED",
        "toCCY": "AED",
        "amountFrom": 12345.36,
        "amountTo": 222222222222222.34,
        "exchangeRate": 3333333333333330.69,
        "effectiveDate": "20210324",
        "feeType": "Bahtnet Fee"
    }
    
}