// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fee/inward/v1/iwrm": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "InwardFee"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consolidated_feature_inwardfee_model.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseDetail": {
                                            "$ref": "#/definitions/consolidated_feature_inwardfee_model.Response"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/fee/outward/v1/branch": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Branch"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consolidated_domain_outward_model.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseDetail": {
                                            "$ref": "#/definitions/consolidated_domain_outward_model.Response"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/fee/v1/promotioncode": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fee"
                ],
                "parameters": [
                    {
                        "description": "Request",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consolidated_domain_fee_model.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseDetail": {
                                            "$ref": "#/definitions/Fee.Response"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "responses": {
                    "200": {
                        "description": "Token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Fee.Response": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "ccy": {
                    "type": "string"
                },
                "proRefID": {
                    "type": "string"
                },
                "promotionType": {
                    "type": "string"
                }
            }
        },
        "Response": {
            "type": "object",
            "properties": {
                "responseCode": {
                    "type": "string"
                },
                "responseDesc": {
                    "type": "string"
                },
                "responseDetail": {
                    "type": "object"
                }
            }
        },
        "consolidated_domain_fee_model.Request": {
            "type": "object",
            "properties": {
                "refId": {
                    "type": "string"
                },
                "reqDetail": {
                    "$ref": "#/definitions/model.RequestDetail"
                },
                "transDate": {
                    "type": "string"
                },
                "transTime": {
                    "type": "string"
                }
            }
        },
        "consolidated_domain_inward_model.ReqDetail": {
            "type": "object",
            "properties": {
                "accountNo": {
                    "type": "string"
                },
                "amountFrom": {
                    "type": "number"
                },
                "amountTo": {
                    "type": "number"
                },
                "benCountry": {
                    "type": "string"
                },
                "chargeType": {
                    "type": "string"
                },
                "cifNo": {
                    "type": "string"
                },
                "depositWithdraw": {
                    "type": "string"
                },
                "effectiveDate": {
                    "type": "string"
                },
                "exchangeRate": {
                    "type": "number"
                },
                "feeChannel": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                },
                "fromCCY": {
                    "type": "string"
                },
                "orderingType": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "searchPayInFull": {
                    "type": "string"
                },
                "toCCY": {
                    "type": "string"
                },
                "transactionType": {
                    "type": "string"
                }
            }
        },
        "consolidated_domain_inward_model.Request": {
            "type": "object",
            "properties": {
                "channelID": {
                    "type": "string"
                },
                "refId": {
                    "type": "string"
                },
                "reqDetail": {
                    "$ref": "#/definitions/consolidated_domain_inward_model.ReqDetail"
                },
                "transDate": {
                    "type": "string"
                },
                "transTime": {
                    "type": "string"
                }
            }
        },
        "consolidated_domain_inward_model.Response": {
            "type": "object",
            "properties": {
                "feeAmount": {
                    "type": "number"
                },
                "feeCCY": {
                    "type": "string"
                },
                "feeCategory": {
                    "type": "string"
                },
                "feeRefID": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                }
            }
        },
        "consolidated_domain_outward_model.ReqDetail": {
            "type": "object",
            "properties": {
                "accountNo": {
                    "type": "string"
                },
                "amountFrom": {
                    "type": "number"
                },
                "amountTo": {
                    "type": "number"
                },
                "benCountry": {
                    "type": "string"
                },
                "chargeType": {
                    "type": "string"
                },
                "cifNo": {
                    "type": "string"
                },
                "effectiveDate": {
                    "type": "string"
                },
                "exchangeRate": {
                    "type": "number"
                },
                "feeChannel": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                },
                "fromCCY": {
                    "type": "string"
                },
                "orderingType": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "searchPayInFull": {
                    "type": "string"
                },
                "toCCY": {
                    "type": "string"
                },
                "transactionType": {
                    "type": "string"
                }
            }
        },
        "consolidated_domain_outward_model.Request": {
            "type": "object",
            "properties": {
                "channelID": {
                    "type": "string"
                },
                "refId": {
                    "type": "string"
                },
                "reqDetail": {
                    "$ref": "#/definitions/consolidated_domain_outward_model.ReqDetail"
                },
                "transDate": {
                    "type": "string"
                },
                "transTime": {
                    "type": "string"
                }
            }
        },
        "consolidated_domain_outward_model.Response": {
            "type": "object",
            "properties": {
                "feeAmount": {
                    "type": "number"
                },
                "feeCCY": {
                    "type": "string"
                },
                "feeCategory": {
                    "type": "string"
                },
                "feeRefID": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                }
            }
        },
        "consolidated_feature_inwardfee_model.ReqDetail": {
            "type": "object",
            "properties": {
                "accountNo": {
                    "type": "string"
                },
                "amountFrom": {
                    "type": "number"
                },
                "amountTo": {
                    "type": "number"
                },
                "benCountry": {
                    "type": "string"
                },
                "chargeType": {
                    "type": "string"
                },
                "cifNo": {
                    "type": "string"
                },
                "depositWithdraw": {
                    "type": "string"
                },
                "effectiveDate": {
                    "type": "string"
                },
                "exchangeRate": {
                    "type": "number"
                },
                "feeChannel": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                },
                "fromCCY": {
                    "type": "string"
                },
                "orderingType": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "searchPayInFull": {
                    "type": "string"
                },
                "toCCY": {
                    "type": "string"
                },
                "transactionType": {
                    "type": "string"
                }
            }
        },
        "consolidated_feature_inwardfee_model.Request": {
            "type": "object",
            "properties": {
                "channelID": {
                    "type": "string"
                },
                "refId": {
                    "type": "string"
                },
                "reqDetail": {
                    "$ref": "#/definitions/consolidated_feature_inwardfee_model.ReqDetail"
                },
                "transDate": {
                    "type": "string"
                },
                "transTime": {
                    "type": "string"
                }
            }
        },
        "consolidated_feature_inwardfee_model.Response": {
            "type": "object",
            "properties": {
                "feeAmount": {
                    "type": "number"
                },
                "feeCCY": {
                    "type": "string"
                },
                "feeCategory": {
                    "type": "string"
                },
                "feeRefID": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                }
            }
        },
        "consolidated_feature_outwardfee_model.ReqDetail": {
            "type": "object",
            "properties": {
                "accountNo": {
                    "type": "string"
                },
                "amountFrom": {
                    "type": "number"
                },
                "amountTo": {
                    "type": "number"
                },
                "benCountry": {
                    "type": "string"
                },
                "chargeType": {
                    "type": "string"
                },
                "cifNo": {
                    "type": "string"
                },
                "effectiveDate": {
                    "type": "string"
                },
                "exchangeRate": {
                    "type": "number"
                },
                "feeChannel": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                },
                "fromCCY": {
                    "type": "string"
                },
                "orderingType": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "searchPayInFull": {
                    "type": "string"
                },
                "toCCY": {
                    "type": "string"
                },
                "transactionType": {
                    "type": "string"
                }
            }
        },
        "consolidated_feature_outwardfee_model.Request": {
            "type": "object",
            "properties": {
                "channelID": {
                    "type": "string"
                },
                "refId": {
                    "type": "string"
                },
                "reqDetail": {
                    "$ref": "#/definitions/consolidated_feature_outwardfee_model.ReqDetail"
                },
                "transDate": {
                    "type": "string"
                },
                "transTime": {
                    "type": "string"
                }
            }
        },
        "consolidated_feature_outwardfee_model.Response": {
            "type": "object",
            "properties": {
                "feeAmount": {
                    "type": "number"
                },
                "feeCCY": {
                    "type": "string"
                },
                "feeCategory": {
                    "type": "string"
                },
                "feeRefID": {
                    "type": "string"
                },
                "feeType": {
                    "type": "string"
                }
            }
        },
        "model.RequestDetail": {
            "type": "object",
            "properties": {
                "FeeComAmount": {
                    "type": "number"
                },
                "channel": {
                    "type": "string"
                },
                "chargeType": {
                    "type": "string"
                },
                "cifNo": {
                    "type": "string"
                },
                "effectiveDate": {
                    "type": "string"
                },
                "exchangeRate": {
                    "type": "number"
                },
                "feeOutwardAmount": {
                    "type": "number"
                },
                "fromCCY": {
                    "type": "string"
                },
                "orderingType": {
                    "type": "string"
                },
                "product": {
                    "type": "string"
                },
                "promotionCode": {
                    "type": "string"
                },
                "sof": {
                    "type": "string"
                },
                "toCCY": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "Bearer token"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Consolidated API",
	Description: "(◍•ᴗ•◍)❤",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
